import { Flame } from "lucide-react";
import { Link } from "wouter";

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <header className="w-full border-b border-border px-6 py-4 flex items-center gap-3">
        <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
          <Flame size={20} className="text-primary" />
          <span className="font-bold font-display text-lg">RoastersAI</span>
        </Link>
      </header>

      <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-12 flex flex-col gap-8">
        <div>
          <h1 className="text-4xl font-bold font-display text-foreground mb-2">About RoastersAI 🔥</h1>
          <p className="text-muted-foreground text-sm">The world's most savage AI roast generator</p>
        </div>

        <p className="text-base leading-relaxed text-foreground/90">
          <strong>RoastersAI</strong> is the world's most savage AI-powered roast generator — built purely for laughs, not feelings. We harness cutting-edge AI to craft personalised, brutally funny roasts based on your name, city, job, relationship status, and personality.
        </p>

        <div className="flex flex-col gap-6">
          <div className="p-5 rounded-xl border border-border bg-card">
            <h2 className="font-bold text-primary mb-2 text-lg">7 Languages Supported</h2>
            <p className="text-sm leading-relaxed text-foreground/80">
              🇺🇸 English · 🇮🇳 Hindi · 🇵🇰 Roman Urdu · 🇪🇸 Spanish · 🇫🇷 French · 🇩🇪 German · 🇧🇷 Portuguese — because everyone deserves to be roasted in their mother tongue.
            </p>
          </div>

          <div className="p-5 rounded-xl border border-border bg-card">
            <h2 className="font-bold text-primary mb-2 text-lg">How It Works</h2>
            <p className="text-sm leading-relaxed text-foreground/80">
              You fill in a few details about yourself. Our AI studies every embarrassing fact you've shared and spits out a roast so accurate it'll make you question your life choices. Results may cause uncontrollable laughter, mild existential crises, or both.
            </p>
          </div>

          <div className="p-5 rounded-xl border border-border bg-card">
            <h2 className="font-bold text-primary mb-2 text-lg">Pick Your Style</h2>
            <p className="text-sm leading-relaxed text-foreground/80">
              Choose from <strong>Friendly</strong> (soft jabs), <strong>Savage</strong> (no mercy), <strong>Dark</strong> (pitch-black humour), or <strong>Desi</strong> (pure desi tadka). Each style is a completely different flavour of roast.
            </p>
          </div>

          <div className="p-5 rounded-xl border border-border bg-card">
            <h2 className="font-bold text-primary mb-2 text-lg">Hall of Shame Leaderboard</h2>
            <p className="text-sm leading-relaxed text-foreground/80">
              The most fire-voted roasts of the day get ranked on our live Hall of Shame. Vote 🔥 on Live Feed cards to crown the most savage roast of the day.
            </p>
          </div>
        </div>

        <p className="text-sm text-muted-foreground italic border-l-2 border-primary pl-4">
          Disclaimer: All roasts are 100% fictional and generated by AI for entertainment only. Please don't take it personally.
        </p>

        <Link href="/" className="inline-flex items-center gap-2 text-primary hover:underline font-medium text-sm w-fit">
          ← Back to RoastersAI
        </Link>
      </main>

      <footer className="w-full py-6 border-t border-border bg-card text-center text-xs text-muted-foreground">
        RoastersAI © {new Date().getFullYear()} · <Link href="/privacy-policy" className="hover:text-primary transition-colors">Privacy Policy</Link> · <Link href="/contact" className="hover:text-primary transition-colors">Contact</Link>
      </footer>
    </div>
  );
}
